### PR TITLE
Point

### PR DESCRIPTION
**Pull request by ToMoClone**
This change is [Reviewable](https://reviewable.io/reviews/natsukagami/tet-school-2017/4)

### CODE REVIEW

**Comment by natsukagami** [comment]
Code đâu, sol đâu?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 0 at r1](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/4#-KafcvORkpOYtTtS79kS:-KafcvORkpOYtTtS79kT:bcqal8o) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/d94be30d43bf02c3062c266d3300e3f859111765/README.md#L0)):*
Cái éo gì đây, xóa file readme?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/4#-:-Kafcze7ox7UI7Jh-Yew:bi3mo51)*

**Comment by phucdtd** [comment]
@natsukagami nó mess-up với cái file cả sáng nay, vừa e sync lại cho thì vẫn còn mấy cái unchanged a chỉ cần disapprove là được mà.

**Comment by phucdtd** [comment]
*[README.md, line  at r1](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/4#-KafcvORkpOYtTtS79kS:-KafelO3G4PmkPJP69NU:b-1w0e5r) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/d94be30d43bf02c3062c266d3300e3f859111765/README.md#L)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

Cái éo gì đây, xóa file readme?
</blockquote></details>

disapprove this pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/4)*

**Comment by natsukagami** [comment]
Disapproved

**Pull request closed without merging**
