### PR TITLE
Update point.cpp & point.md - By TM

### PR DESCRIPTION
**Pull request by phucdtd**
#By Thành Minh

Vì TM mãi chưa làm được nên là t làm hộ. TM cứ sửa thoải mái t edit hộ cho.

---
This change is [Reviewable](https://reviewable.io/reviews/natsukagami/tet-school-2017/6)

### CODE REVIEW

**Comment by natsukagami** [comment]
File code để luôn vào `LAH15/20170116` đi

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-:-KagNKsrzKYr8Ue93XzF:b-7kpug4)*

**Comment by phucdtd** [comment]
@natsukagami ok a.

**Comment by natsukagami** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[LAH15/20170116/POINT.md, line 4 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KagSTxN4hoFIcvCY6fB:-KagSTxN4hoFIcvCY6fC:bsaz5e6) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/2ec8db46071f7ed7c861ec9502b278f8916335e2/LAH15/20170116/POINT.md#L4)):*
> ```Markdown
> ## Nguyễn Thành Minh
> 
> ## Problem Statement
> ```

Chưa tóm tắt đề

---

*[LAH15/20170116/POINT.md, line 6 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KagSWfxYPszygUQLddL:-KagSWfxYPszygUQLddM:bshknpu) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/2ec8db46071f7ed7c861ec9502b278f8916335e2/LAH15/20170116/POINT.md#L6)):*
> ```Markdown
> ## Problem Statement
> 
> ## Required Skills
> ```

Chưa tóm tắt kĩ năng

---

*[LAH15/20170116/POINT.md, line 8 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KagSYKdcks6TKaUxRi7:-KagSYKdcks6TKaUxRi8:b-1p5r5l) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/2ec8db46071f7ed7c861ec9502b278f8916335e2/LAH15/20170116/POINT.md#L8)):*
> ```Markdown
> ## Required Skills
> 
> ## Step-by-Step Solution
> ```

Chưa chữa bài

---

*[LAH15/20170116/POINT.md, line 10 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KagSZbJ0KdqP8iEY4Z6:-KagSZbJ0KdqP8iEY4Z7:b-pzqxr0) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/2ec8db46071f7ed7c861ec9502b278f8916335e2/LAH15/20170116/POINT.md#L10)):*
> ```Markdown
> ## Step-by-Step Solution
> 
> ## Conclusion
> ```

Thiếu kết luận

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6)*

**Comment by phucdtd** [comment]
*[LAH15/20170116/POINT.md, line 4 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KagSTxN4hoFIcvCY6fB:-KagT0B9u5ZO-q6_ATe_:b-z2lss2) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/2ec8db46071f7ed7c861ec9502b278f8916335e2/LAH15/20170116/POINT.md#L4)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

Chưa tóm tắt đề
</blockquote></details>

Của TM e ko đụng vào, chờ nó sửa
\

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6)*

**Comment by phucdtd** [comment]
*[LAH15/20170116/POINT.md, line 6 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KagSWfxYPszygUQLddL:-KagT5iD7qTyfFx8RqTR:b2e57qy) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/2ec8db46071f7ed7c861ec9502b278f8916335e2/LAH15/20170116/POINT.md#L6)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

Chưa tóm tắt kĩ năng
</blockquote></details>

Để TM làm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6)*

**Comment by phucdtd** [comment]
*[LAH15/20170116/POINT.md, line 8 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KagSYKdcks6TKaUxRi7:-KagT8VSNpr9t0pkl3qW:bj7wg0y) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/2ec8db46071f7ed7c861ec9502b278f8916335e2/LAH15/20170116/POINT.md#L8)):*
>  
Để TM chữa

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6)*

**Comment by phucdtd** [comment]
*[LAH15/20170116/POINT.md, line 10 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KagSZbJ0KdqP8iEY4Z6:-KagTB7jyMv8WfiCYi9G:b-4d66kq) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/2ec8db46071f7ed7c861ec9502b278f8916335e2/LAH15/20170116/POINT.md#L10)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

Thiếu kết luận
</blockquote></details>

Rồi TM sẽ kết luận

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6)*

**Comment by phucdtd** [comment]
Added ToMo's point.md

**Comment by natsukagami** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[LAH15/20170116/POINT.md, line 11 at r4](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KajNgOK0rm1V2d0_XVP:-KajNgOK0rm1V2d0_XVQ:bffa2z5) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/8f328ddfbf2d2d89e4334a729dc1b93d96e2390c/LAH15/20170116/POINT.md#L11)):*
> ```Markdown
> 
> ## Required Skills
> - Thông thạo 7 Yasuo
> ```

xóa đi em

---

*[LAH15/20170116/POINT.md, line 24 at r4](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KajNphOe7QrVgAluiPi:-KajNphOe7QrVgAluiPj:b-def1zb) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/8f328ddfbf2d2d89e4334a729dc1b93d96e2390c/LAH15/20170116/POINT.md#L24)):*
> ```Markdown
> Chú ý thứ tự ưu tiên xử lí khi các điểm cùng tọa độ: Mút trái trước, điểm mình cần truy vấn rồi mới đến điểm kết thúc.  
> Lí do: Nếu một điểm thuộc đầu mút trái hoặc mút phải của một đoạn thẳng thì nó vẫn thuộc đoạn thẳng. Vì vậy, ta phải tăng số _k_ khi gặp mút trái trước, xử lí truy vấn rồi mới _k_ khi gặp mút phải để tránh tính thiếu và tính thừa.  
> Để cho dễ hiểu hơn, các bạn có thể xem code ở [đây](http://ideone.com/mOVASq).
> ```

Sao không lấy link file code https://github.com/natsukagami/tet-school-2017/tree/master/LAH15/20170116/point.cpp

---

*[LAH15/20170116/POINT.md, line 30 at r4](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KajOJCLOQeSo5g7xCNZ:-KajOJCLOQeSo5g7xCN_:bdwr1sf) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/8f328ddfbf2d2d89e4334a729dc1b93d96e2390c/LAH15/20170116/POINT.md#L30)):*
> ```Markdown
> * Đây là một bài sử dụng một tư tưởng rất hay gặp và tư tưởng đầu mút trái và đầu mút phải có thể xử lí độc lập có thể áp dụng để giải rất nhiều bài
> * Cẩn thận khi cài đặt, cần xét kĩ lưỡng ưu tiên xử lí điểm loại nào trước
> * Thông thạo 7 Yasuo rất dễ gây ảo tưởng sức mạnh, gây nên hậu quả khôn lường. Luôn luôn suy nghĩ trước khi pick Yasuo nếu bạn đang đánh rank
> ```

Xóa đi em 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6)*

**Comment by natsukagami** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6)*

**Comment by phucdtd** [comment]
*[LAH15/20170116/POINT.md, line 24 at r4](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-KajNphOe7QrVgAluiPi:-KakacVKXxFikQXhNJIj:bi05k83) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/8f328ddfbf2d2d89e4334a729dc1b93d96e2390c/LAH15/20170116/POINT.md#L24)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

Sao không lấy link file code https://github.com/natsukagami/tet-school-2017/tree/master/LAH15/20170116/point.cpp
</blockquote></details>

e tưởng chưa đc merge thì nó chưa trong repo?
Other things fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6)*

**Comment by natsukagami** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/6#-:-Kakh5lhurkPQ0ebtWnx:bnfp4nl)*

**Pull request merged**
